{
  try {
    run2();
  }
 catch (  RuntimeException re) {
    _log.error("timer error",re);
    throw re;
  }
}
